// Generates lib/core/assets/app_assets.dart from the files under assets/.
//
// Run after adding, renaming or removing an asset:
//   dart run tool/generate_app_assets.dart
//
// Also verifies every asset folder is declared in pubspec.yaml.
import 'dart:io';

const _groups = <String, String>{
  'assets/icons': 'icon',
  'assets/illustrations': 'illustration',
};

void main() {
  final buffer = StringBuffer()
    ..writeln('// GENERATED by tool/generate_app_assets.dart — do not edit.')
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln()
    ..writeln('/// Typed paths for every bundled asset. Never use raw asset')
    ..writeln('/// path strings elsewhere in the app.')
    ..writeln('abstract final class AppAssets {');

  final pubspec = File('pubspec.yaml').readAsStringSync();
  final all = <String, List<String>>{};

  for (final MapEntry(key: dir, value: prefix) in _groups.entries) {
    final files =
        Directory(dir)
            .listSync(recursive: true)
            .whereType<File>()
            .where((f) => f.path.endsWith('.svg'))
            .map((f) => f.path.replaceAll(r'\', '/'))
            .toList()
          ..sort();
    final names = <String>[];
    buffer.writeln('  // ---- $dir ----');
    for (final path in files) {
      final folder = path.substring(0, path.lastIndexOf('/') + 1);
      if (!pubspec.contains('- $folder')) {
        stderr.writeln('pubspec.yaml is missing asset folder: $folder');
        exitCode = 1;
      }
      final relative = path
          .substring(dir.length + 1)
          .replaceAll('.svg', '')
          .replaceAll('/', '_');
      final name = _camel('${prefix}_$relative');
      names.add(name);
      buffer.writeln("  static const $name = '$path';");
    }
    all[prefix] = names;
    buffer.writeln();
  }

  for (final MapEntry(key: prefix, value: names) in all.entries) {
    buffer
      ..writeln('  static const all${_pascal(prefix)}s = <String>[')
      ..writeAll(names.map((n) => '    $n,\n'))
      ..writeln('  ];')
      ..writeln();
  }
  buffer.writeln('}');

  File('lib/core/assets/app_assets.dart').writeAsStringSync(buffer.toString());
  stdout.writeln('Wrote ${all.values.fold(0, (a, b) => a + b.length)} assets.');
}

String _camel(String snake) {
  final parts = snake.split('_');
  return parts.first + parts.skip(1).map(_pascal).join();
}

String _pascal(String s) => s.isEmpty ? s : s[0].toUpperCase() + s.substring(1);
