// GENERATED by tool/generate_app_assets.dart — do not edit.
// ignore_for_file: lines_longer_than_80_chars

/// Typed paths for every bundled asset. Never use raw asset
/// path strings elsewhere in the app.
abstract final class AppAssets {
  // ---- assets/icons ----
  static const iconAlertCircle = 'assets/icons/alert_circle.svg';
  static const iconApple = 'assets/icons/apple.svg';
  static const iconBell = 'assets/icons/bell.svg';
  static const iconCalendar = 'assets/icons/calendar.svg';
  static const iconCalendarBold = 'assets/icons/calendar_bold.svg';
  static const iconCalendarCheck = 'assets/icons/calendar_check.svg';
  static const iconCamera = 'assets/icons/camera.svg';
  static const iconChair = 'assets/icons/chair.svg';
  static const iconCheck = 'assets/icons/check.svg';
  static const iconCheckBold = 'assets/icons/check_bold.svg';
  static const iconChevronDown = 'assets/icons/chevron_down.svg';
  static const iconChevronLeft = 'assets/icons/chevron_left.svg';
  static const iconChevronRight = 'assets/icons/chevron_right.svg';
  static const iconClock = 'assets/icons/clock.svg';
  static const iconClose = 'assets/icons/close.svg';
  static const iconEye = 'assets/icons/eye.svg';
  static const iconEyeOff = 'assets/icons/eye_off.svg';
  static const iconFilter = 'assets/icons/filter.svg';
  static const iconGift = 'assets/icons/gift.svg';
  static const iconGlobe = 'assets/icons/globe.svg';
  static const iconGoogle = 'assets/icons/google.svg';
  static const iconHeart = 'assets/icons/heart.svg';
  static const iconHeartFilled = 'assets/icons/heart_filled.svg';
  static const iconHelpCircle = 'assets/icons/help_circle.svg';
  static const iconHome = 'assets/icons/home.svg';
  static const iconHomeBold = 'assets/icons/home_bold.svg';
  static const iconLock = 'assets/icons/lock.svg';
  static const iconLogout = 'assets/icons/logout.svg';
  static const iconMapPin = 'assets/icons/map_pin.svg';
  static const iconMessage = 'assets/icons/message.svg';
  static const iconMoney = 'assets/icons/money.svg';
  static const iconMoon = 'assets/icons/moon.svg';
  static const iconNavigation = 'assets/icons/navigation.svg';
  static const iconPhone = 'assets/icons/phone.svg';
  static const iconPlay = 'assets/icons/play.svg';
  static const iconPlus = 'assets/icons/plus.svg';
  static const iconRefresh = 'assets/icons/refresh.svg';
  static const iconRepeat = 'assets/icons/repeat.svg';
  static const iconScissors = 'assets/icons/scissors.svg';
  static const iconSearch = 'assets/icons/search.svg';
  static const iconSearchBold = 'assets/icons/search_bold.svg';
  static const iconSettings = 'assets/icons/settings.svg';
  static const iconShare = 'assets/icons/share.svg';
  static const iconStar = 'assets/icons/star.svg';
  static const iconStarFilled = 'assets/icons/star_filled.svg';
  static const iconStore = 'assets/icons/store.svg';
  static const iconSun = 'assets/icons/sun.svg';
  static const iconSunset = 'assets/icons/sunset.svg';
  static const iconTrash = 'assets/icons/trash.svg';
  static const iconUser = 'assets/icons/user.svg';
  static const iconUserBold = 'assets/icons/user_bold.svg';
  static const iconUsers = 'assets/icons/users.svg';
  static const iconWifiOff = 'assets/icons/wifi_off.svg';

  // ---- assets/illustrations ----
  static const illustrationEmptyBookings =
      'assets/illustrations/empty_bookings.svg';
  static const illustrationFavoritesEmpty =
      'assets/illustrations/favorites_empty.svg';
  static const illustrationNoInternet = 'assets/illustrations/no_internet.svg';
  static const illustrationNotificationsEmpty =
      'assets/illustrations/notifications_empty.svg';
  static const illustrationOnboardingChooseBarber =
      'assets/illustrations/onboarding_choose_barber.svg';
  static const illustrationOnboardingChooseBarberBackground =
      'assets/illustrations/onboarding_choose_barber/background.svg';
  static const illustrationOnboardingChooseBarberChair =
      'assets/illustrations/onboarding_choose_barber/chair.svg';
  static const illustrationOnboardingChooseBarberScissorsBladeBottom =
      'assets/illustrations/onboarding_choose_barber/scissors_blade_bottom.svg';
  static const illustrationOnboardingChooseBarberScissorsBladeTop =
      'assets/illustrations/onboarding_choose_barber/scissors_blade_top.svg';
  static const illustrationOnboardingChooseBarberStarLeft =
      'assets/illustrations/onboarding_choose_barber/star_left.svg';
  static const illustrationOnboardingChooseBarberStarRight =
      'assets/illustrations/onboarding_choose_barber/star_right.svg';
  static const illustrationOnboardingFindSalons =
      'assets/illustrations/onboarding_find_salons.svg';
  static const illustrationOnboardingFindSalonsPin =
      'assets/illustrations/onboarding_find_salons/pin.svg';
  static const illustrationOnboardingFindSalonsScene =
      'assets/illustrations/onboarding_find_salons/scene.svg';
  static const illustrationOnboardingLiveQueue =
      'assets/illustrations/onboarding_live_queue.svg';
  static const illustrationOnboardingLiveQueueClockHands =
      'assets/illustrations/onboarding_live_queue/clock_hands.svg';
  static const illustrationOnboardingLiveQueueScene =
      'assets/illustrations/onboarding_live_queue/scene.svg';
  static const illustrationQueueJoined =
      'assets/illustrations/queue_joined.svg';
  static const illustrationRatingSent = 'assets/illustrations/rating_sent.svg';
  static const illustrationSearchNoResults =
      'assets/illustrations/search_no_results.svg';
  static const illustrationYourTurn = 'assets/illustrations/your_turn.svg';

  static const allIcons = <String>[
    iconAlertCircle,
    iconApple,
    iconBell,
    iconCalendar,
    iconCalendarBold,
    iconCalendarCheck,
    iconCamera,
    iconChair,
    iconCheck,
    iconCheckBold,
    iconChevronDown,
    iconChevronLeft,
    iconChevronRight,
    iconClock,
    iconClose,
    iconEye,
    iconEyeOff,
    iconFilter,
    iconGift,
    iconGlobe,
    iconGoogle,
    iconHeart,
    iconHeartFilled,
    iconHelpCircle,
    iconHome,
    iconHomeBold,
    iconLock,
    iconLogout,
    iconMapPin,
    iconMessage,
    iconMoney,
    iconMoon,
    iconNavigation,
    iconPhone,
    iconPlay,
    iconPlus,
    iconRefresh,
    iconRepeat,
    iconScissors,
    iconSearch,
    iconSearchBold,
    iconSettings,
    iconShare,
    iconStar,
    iconStarFilled,
    iconStore,
    iconSun,
    iconSunset,
    iconTrash,
    iconUser,
    iconUserBold,
    iconUsers,
    iconWifiOff,
  ];

  static const allIllustrations = <String>[
    illustrationEmptyBookings,
    illustrationFavoritesEmpty,
    illustrationNoInternet,
    illustrationNotificationsEmpty,
    illustrationOnboardingChooseBarber,
    illustrationOnboardingChooseBarberBackground,
    illustrationOnboardingChooseBarberChair,
    illustrationOnboardingChooseBarberScissorsBladeBottom,
    illustrationOnboardingChooseBarberScissorsBladeTop,
    illustrationOnboardingChooseBarberStarLeft,
    illustrationOnboardingChooseBarberStarRight,
    illustrationOnboardingFindSalons,
    illustrationOnboardingFindSalonsPin,
    illustrationOnboardingFindSalonsScene,
    illustrationOnboardingLiveQueue,
    illustrationOnboardingLiveQueueClockHands,
    illustrationOnboardingLiveQueueScene,
    illustrationQueueJoined,
    illustrationRatingSent,
    illustrationSearchNoResults,
    illustrationYourTurn,
  ];
}
